wandb_version: 1

D_steps_per_G:
  desc: null
  value: 1
N_in_channels:
  desc: null
  value: 5
N_out_channels:
  desc: null
  value: 5
Nsamples:
  desc: null
  value: 8192
Nsamples_val:
  desc: null
  value: 512
_wandb:
  desc: null
  value:
    cli_version: 0.12.13
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.12
    start_time: 1658895947
    t:
      1:
      - 1
      - 41
      - 55
      3:
      - 5
      - 13
      - 16
      4: 3.8.12
      5: 0.12.13
      8:
      - 8
add_grid:
  desc: null
  value: false
additive_noise:
  desc: null
  value: false
alpha:
  desc: null
  value: '1.0'
base_batch_size:
  desc: null
  value: 64
batch_size:
  desc: null
  value: 16
beta1:
  desc: null
  value: '0.5'
beta2:
  desc: null
  value: '0.999'
box_size:
  desc: null
  value:
  - 512
  - 512
  - 512
cat_inp:
  desc: null
  value: false
conttime:
  desc: null
  value: false
crop_size_x:
  desc: null
  value: null
crop_size_y:
  desc: null
  value: null
data_loader_config:
  desc: null
  value: lowmem
data_size:
  desc: null
  value: 128
downsamp:
  desc: null
  value: true
dt:
  desc: null
  value: 1
enable_amp:
  desc: null
  value: false
enable_apex:
  desc: null
  value: false
enable_benchy:
  desc: null
  value: false
enable_jit:
  desc: null
  value: false
entity:
  desc: null
  value: weatherbenching
expdir:
  desc: null
  value: /logs
full_scale:
  desc: null
  value: true
gan_mode:
  desc: null
  value: hinge
global_batch_size:
  desc: null
  value: 64
global_means_path:
  desc: null
  value: /pscratch/sd/s/shas1693/data/era5/global_means.npy
global_stds_path:
  desc: null
  value: /pscratch/sd/s/shas1693/data/era5/global_stds.npy
img_size:
  desc: null
  value:
  - 512
  - 512
  - 512
in_channels:
  desc: null
  value:
  - 0
  - 1
  - 2
  - 3
  - 17
  - 18
  - 19
init_type:
  desc: null
  value: xavier
init_variance:
  desc: null
  value: '0.02'
input_nc:
  desc: null
  value: 5
lambda_feat:
  desc: null
  value: '0.5'
lambda_kld:
  desc: null
  value: '0.05'
lambda_l1:
  desc: null
  value: '1.0'
lambda_rho:
  desc: null
  value: 0
lambda_spec:
  desc: null
  value: '1.0'
log_to_screen:
  desc: null
  value: true
log_to_wandb:
  desc: null
  value: true
lr:
  desc: null
  value: '0.0002'
lr_schedule:
  desc: null
  value:
    end_lr: '0.0'
    scaling: sqrt
    start_lr: '0.0002'
    warmup_steps: 128
max_path:
  desc: null
  value: /pscratch/sd/s/shas1693/data/era5/maxs.npy
min_path:
  desc: null
  value: /pscratch/sd/s/shas1693/data/era5/mins.npy
model:
  desc: null
  value: pix2pix
n_history:
  desc: null
  value: 0
n_layers_D:
  desc: null
  value: 4
ndf:
  desc: null
  value: 64
nef:
  desc: null
  value: 16
netD:
  desc: null
  value: multiscale
netG:
  desc: null
  value: tsit
ngf:
  desc: null
  value: 64
niter:
  desc: null
  value: 100
niter_decay:
  desc: null
  value: 50
no_TTUR:
  desc: null
  value: true
no_ganFeat_loss:
  desc: null
  value: false
no_ss:
  desc: null
  value: true
norm_D:
  desc: null
  value: spectralinstance
norm_E:
  desc: null
  value: spectralinstance
norm_G:
  desc: null
  value: spectralfadebatch3x3
norm_S:
  desc: null
  value: spectralinstance
normalization:
  desc: null
  value: zscore
num_D:
  desc: null
  value: 2
num_data_workers:
  desc: null
  value: 16
num_epochs:
  desc: null
  value: 60
num_upsampling_blocks:
  desc: null
  value: 6
optimizer:
  desc: null
  value: adam
out_channels:
  desc: null
  value:
  - 0
output_nc:
  desc: null
  value: 5
precip:
  desc: null
  value: /pscratch/sd/p/pharring/ERA5/precip/total_precipitation
precip_eps:
  desc: null
  value: 1e-05
project:
  desc: null
  value: Nyx-TSIT
roll:
  desc: null
  value: false
save_checkpoint:
  desc: null
  value: true
time_means_path:
  desc: null
  value: /pscratch/sd/s/shas1693/data/era5/time_means.npy
train_path:
  desc: null
  value: /pscratch/sd/c/cjacobus/Nyx_512/train_s1_512_hydro.h5
use_cache:
  desc: null
  value: null
use_l1_loss:
  desc: null
  value: false
use_periodic_padding:
  desc: null
  value: true
use_spec_loss:
  desc: null
  value: false
use_vae:
  desc: null
  value: false
val_path:
  desc: null
  value: /pscratch/sd/c/cjacobus/Nyx_512/train_s1_512_hydro.h5
weight_init:
  desc: null
  value:
    conv_bias: '0.0'
    conv_init: normal
    conv_scale: '0.02'
z_dim:
  desc: null
  value: 256
